"HH"
{   
    //Базовые (для работы игры)
    "generic_hidden" "generic_hidden"
    "default_attack" "default_attack"
    "backdoor_protection" "backdoor_protection"
    "backdoor_protection_in_base" "backdoor_protection_in_base"

    //Вспомогательные (скилл нужен для работы других скиллов)
    "phoenix_sun_ray_toggle_move" "phoenix_sun_ray_toggle_move"
    "earth_spirit_stone_caller" "earth_spirit_stone_caller"
    "ember_spirit_activate_fire_remnant" "ember_spirit_activate_fire_remnant"
    "faceless_void_time_walk_reverse" "faceless_void_time_walk_reverse"
    "lone_druid_spirit_bear_return" "lone_druid_spirit_bear_return"
    "elder_titan_echo_stomp_spirit" "elder_titan_echo_stomp_spirit"
    "elder_titan_return_spirit" "elder_titan_return_spirit"
	"elder_titan_natural_order_spirit" "elder_titan_natural_order_spirit"
    "warlock_imp_explode_major" "warlock_imp_explode_major" 
    "templar_assassin_trap" "templar_assassin_trap"
    "treant_lifebomb_explode" "treant_lifebomb_explode"
    "snapfire_spit_creep" "snapfire_spit_creep"
    "magnus_magnetic_horn" "magnus_magnetic_horn"
    "lich_variant_ice_rite" "lich_variant_ice_rite"
    "warlock_imp_explode" "warlock_imp_explode"

    //Баганые (вылеты и неправильная работа)
    "meepo_divided_we_stand" "meepo_divided_we_stand" //не получается убить клонов мипо после смерти
    "tornado_tempest" "tornado_tempest" //бесконечное торнадо
    "invoker_quas" "invoker_quas"
    "invoker_wex" "invoker_wex"
    "invoker_exort" "invoker_exort"
    "invoker_invoke" "invoker_invoke"
    "ancient_golem_rockslide" "ancient_golem_rockslide" //пустой скилл
    "chen_martyrdom" "chen_martyrdom" //вылет при использовании на себя?
    "wisp_spirits" "wisp_spirits" //вылет при выдаче
    "bounty_hunter_lookout" "bounty_hunter_lookout"
    "techies_remote_mines_self_detonate" "techies_remote_mines_self_detonate"
    "lone_druid_spirit_bear_fetch" "lone_druid_spirit_bear_fetch"
    "lone_druid_spirit_link" "lone_druid_spirit_link"
    "spawnlord_master_bash" "spawnlord_master_bash"
    "muerta_ofrenda" "muerta_ofrenda"
    "lone_druid_rabid" "lone_druid_rabid"
    "lone_druid_spirit_bear_defender" "lone_druid_spirit_bear_defender"
    "monkey_king_wukongs_command" "monkey_king_wukongs_command" //вылет из-за спавна копий
    "elder_titan_echo_stomp" "elder_titan_echo_stomp" //не работает
    "ogre_magi_multicast" "ogre_magi_multicast"

    //Временно неиграбельно? (помню что раньше этот скилл работал)
    "venomancer_poison_nova" "venomancer_poison_nova" //патч 7.36c
    "chen_test_of_faith_teleport" "chen_test_of_faith_teleport" //патч 7.36c
    
}