"HH"
{
    // скейл дмг
    "true_form_bonus_building_damage" "true_form_bonus_building_damage"
    "bonus_building_damage" "bonus_building_damage"
    "attack_amp" "attack_amp"
    "toss_damage_bonus_pct" "toss_damage_bonus_pct"
    "bonus_land_damage_pct" "bonus_land_damage_pct"
    "bonus_damage_pct" "bonus_damage_pct"
    "damage_percent_add" "damage_percent_add"
    "frost_blast_damage_percent" "frost_blast_damage_percent"
    "inner_radius_bonus_damage_pct" "inner_radius_bonus_damage_pct"
    "base_damage_pct" "base_damage_pct"
    "max_mana_as_damage_pct" "max_mana_as_damage_pct"
    "damage_echo_pct" "damage_echo_pct"
    "damage_reflect_pct" "damage_reflect_pct"
    "tick_attack_damage_pct" "tick_attack_damage_pct"
    "creep_multiplier" "creep_multiplier"
    "damage_percent" "damage_percent"
    "scepter_pct_damage" "scepter_pct_damage"
    "skeleton_bonus_hero_damage" "skeleton_bonus_hero_damage"
    "cursed_damage_pct" "cursed_damage_pct"
    "creep_damage_multiplier" "creep_damage_multiplier"
    "damage_amp" "damage_amp"
    "str_percentage" "str_percentage"
    "aura_damage" "aura_damage"
    "burn_damage" "burn_damage"
    "bleed_health_pct" "bleed_health_pct"
    "tower_dps_pct" "tower_dps_pct"
    // скейл крита
    "strike_crit_mult" "strike_crit_mult"
    "crit_min" "crit_min"
    "crit_max" "crit_max"
    "crit_mult" "crit_mult"
    "wraith_crit_bonus" "wraith_crit_bonus"
    // вампиризм
    "lifesteal" "lifesteal"
    // хил
    "building_healing_pct" "building_healing_pct"
    // хз
    "spring_channel_pct" "spring_channel_pct"
    "allied_damage_pct" "allied_damage_pct"
    // сжигание маны
    "mana_burn_pct" "mana_burn_pct"
    //скейл от процента здоровья
    "current_health_pct" "current_health_pct"
    // Снижение пополенения здоровья
    "restoration_reduction" "restoration_reduction"
    "heal_reduction" "heal_reduction"
    //разное
    "strength_share_percent" "strength_share_percent"
}