"HH"
{
    // скейл дмг
    "true_form_bonus_building_damage" "true_form_bonus_building_damage"
    "bonus_building_damage" "bonus_building_damage"
    "attack_amp" "attack_amp"
    "toss_damage_bonus_pct" "toss_damage_bonus_pct"
    "bonus_land_damage_pct" "bonus_land_damage_pct"
    "bonus_damage_pct" "bonus_damage_pct"
    "damage_percent_add" "damage_percent_add"
    "frost_blast_damage_percent" "frost_blast_damage_percent"
    "inner_radius_bonus_damage_pct" "inner_radius_bonus_damage_pct"
    "base_damage_pct" "base_damage_pct"
    "max_mana_as_damage_pct" "max_mana_as_damage_pct"
    "damage_echo_pct" "damage_echo_pct"
    "damage_reflect_pct" "damage_reflect_pct"
    "tick_attack_damage_pct" "tick_attack_damage_pct"
    // скейл крита
    "creep_damage_multiplier" "creep_damage_multiplier"
    "strike_crit_mult" "strike_crit_mult"
    // вампиризм
    "lifesteal" "lifesteal"
    // хил
    "building_healing_pct" "building_healing_pct"
    // хз
    "spring_channel_pct" "spring_channel_pct"
    // сжигание маны
    "mana_burn_pct" "mana_burn_pct"
}