// speed
"HH"
{
    "move_speed" "move_speed"
    "treant_movespeed" "treant_movespeed"
    "sand_storm_move_speed_pct" "sand_storm_move_speed_pct"
    "sand_storm_move_speed_bonus_when_outside_radius" "sand_storm_move_speed_bonus_when_outside_radius"
    "bonus_movement_speed" "bonus_movement_speed"
    "movement_speed" "movement_speed"
    "Exclude" {
        "spring_leap_speed" "spring_leap_speed"
        "leap_speed" "leap_speed"
        "burrow_speed_scepter" "burrow_speed_scepter"
        "hook_speed" "hook_speed"
    }
}